/* 
Copyright (c) 2018 Swift Models Generated from JSON powered by http://www.json4swift.com

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

For support, please feel free to contact me at https://www.linkedin.com/in/syedabsar

*/

import Foundation
struct Access : Codable {
	let vwRuleManagement : Int?
	let vPersonMonthlyReward : Int?
	let product : Int?
	let smsContent : Int?
	let vProductTop10Quantity : Int?
	let eventReport : Int?
	let ccard : Int?
	let organizationConfig : Int?
	let sP_RewardCalc : Int?
	let vUserInfoDetail : Int?
	let rewardBalanceAssignedPos : Int?
	let vProductTop10Amount : Int?
	let personPropertyType : Int?
	let lotteryIncludedPerson : Int?
	let vPersonProfileRatio : Int?
	let vOrganizationSurvey : Int?
	let vwEventTransaction : Int?
	let vOrganizationRewardList : Int?
	let vPersonLevelCount : Int?
	let personLevelAssign : Int?
	let getPersonBrief : Int?
	let personRewardConversion : Int?
	let transactionPropertyType : Int?
	let rewardBalance : Int?
	let errorLog : Int?
	let vwReward : Int?
	let contentCampaignScoreDetail : Int?
	let scenario : Int?
	let pos : Int?
	let contentCampaign : Int?
	let vPersonProductQtyAmount : Int?
	let person : Int?
	let person_Club_Info : Int?
	let usecaseAction : Int?
	let bank : Int?
	let organization : Int?
	let pageContent : Int?
	let sysField : Int?
	let transactionUsedCredit : Int?
	let userOrganization : Int?
	let posType : Int?
	let transactionMaster : Int?
	let vwTransactionMaster : Int?
	let passenger : Int?
	let vwOrganizationProductCategory : Int?
	let vPersonLevel : Int?
	let rewardsListSerial : Int?
	let vwPerson : Int?
	let ccardClass : Int?
	let vwTransactionDetail : Int?
	let vPersonRewardCalcDate : Int?
	let vPersonInvitation : Int?
	let organizationSuggestion : Int?
	let event : Int?
	let ccardNA : Int?
	let usecase : Int?
	let vUserInfo : Int?
	let personOrganizationRelation : Int?
	let phoneContact : Int?
	let eventType : Int?
	let comboVal : Int?
	let bankSwitch : Int?
	let dashboard : Int?
	let transactionMasterReport : Int?
	let vPersonRewardEventType : Int?
	let version : Int?
	let vRewardEventType : Int?
	let rewardAction : Int?
	let accessGrp : Int?
	let vwProduct : Int?
	let vwCcardNA : Int?
	let organizationPersonLevel : Int?
	let rewardConversionPopulrty : Int?
	let personProperty : Int?
	let vwRewardConversion : Int?
	let role : Int?
	let rewardType : Int?
	let gallery : Int?
	let productCategory : Int?
	let file : Int?
	let vPersonLevelReward : Int?
	let lMSFunction : Int?
	let personPropertyMapping : Int?
	let action : Int?
	let rewardsList : Int?
	let user : Int?
	let userRoleDataAccess : Int?
	let vPersonPointGrade : Int?
	let systemLog : Int?
	let transactionProperty : Int?
	let rewardConversion : Int?
	let userReport : Int?
	let vwCcard : Int?
	let news : Int?
	let vwRewardsList : Int?
	let profile_Menu : Int?
	let transactionDetail : Int?
	let vwCoUser : Int?
	let ruleManagement : Int?
	let organizationProductCategory : Int?
	let comment : Int?
	let vwRewardConversionFormula : Int?
	let organizationPersonGroup : Int?
	let ccardSegment : Int?
	let answer : Int?
	let rewardConversionFormula : Int?
	let userRole : Int?
	let contentCampaignPost : Int?
	let فرآيندها : Int?
	let vPersonRewards : Int?
	let reward : Int?
	let userRewardDetail : Int?
	let imageLoader : Int?
	let userScenarioLog : Int?
	let location : Int?

	enum CodingKeys: String, CodingKey {

		case vwRuleManagement = "VwRuleManagement"
		case vPersonMonthlyReward = "VPersonMonthlyReward"
		case product = "Product"
		case smsContent = "SmsContent"
		case vProductTop10Quantity = "VProductTop10Quantity"
		case eventReport = "EventReport"
		case ccard = "Ccard"
		case organizationConfig = "OrganizationConfig"
		case sP_RewardCalc = "SP_RewardCalc"
		case vUserInfoDetail = "VUserInfoDetail"
		case rewardBalanceAssignedPos = "RewardBalanceAssignedPos"
		case vProductTop10Amount = "VProductTop10Amount"
		case personPropertyType = "PersonPropertyType"
		case lotteryIncludedPerson = "LotteryIncludedPerson"
		case vPersonProfileRatio = "VPersonProfileRatio"
		case vOrganizationSurvey = "VOrganizationSurvey"
		case vwEventTransaction = "VwEventTransaction"
		case vOrganizationRewardList = "VOrganizationRewardList"
		case vPersonLevelCount = "VPersonLevelCount"
		case personLevelAssign = "PersonLevelAssign"
		case getPersonBrief = "GetPersonBrief"
		case personRewardConversion = "PersonRewardConversion"
		case transactionPropertyType = "TransactionPropertyType"
		case rewardBalance = "RewardBalance"
		case errorLog = "ErrorLog"
		case vwReward = "VwReward"
		case contentCampaignScoreDetail = "ContentCampaignScoreDetail"
		case scenario = "Scenario"
		case pos = "Pos"
		case contentCampaign = "ContentCampaign"
		case vPersonProductQtyAmount = "VPersonProductQtyAmount"
		case person = "Person"
		case person_Club_Info = "Person_Club_Info"
		case usecaseAction = "UsecaseAction"
		case bank = "Bank"
		case organization = "Organization"
		case pageContent = "PageContent"
		case sysField = "SysField"
		case transactionUsedCredit = "TransactionUsedCredit"
		case userOrganization = "UserOrganization"
		case posType = "PosType"
		case transactionMaster = "TransactionMaster"
		case vwTransactionMaster = "VwTransactionMaster"
		case passenger = "Passenger"
		case vwOrganizationProductCategory = "VwOrganizationProductCategory"
		case vPersonLevel = "VPersonLevel"
		case rewardsListSerial = "RewardsListSerial"
		case vwPerson = "VwPerson"
		case ccardClass = "CcardClass"
		case vwTransactionDetail = "VwTransactionDetail"
		case vPersonRewardCalcDate = "VPersonRewardCalcDate"
		case vPersonInvitation = "VPersonInvitation"
		case organizationSuggestion = "OrganizationSuggestion"
		case event = "Event"
		case ccardNA = "CcardNA"
		case usecase = "Usecase"
		case vUserInfo = "VUserInfo"
		case personOrganizationRelation = "PersonOrganizationRelation"
		case phoneContact = "PhoneContact"
		case eventType = "EventType"
		case comboVal = "ComboVal"
		case bankSwitch = "BankSwitch"
		case dashboard = "Dashboard"
		case transactionMasterReport = "TransactionMasterReport"
		case vPersonRewardEventType = "VPersonRewardEventType"
		case version = "Version"
		case vRewardEventType = "VRewardEventType"
		case rewardAction = "RewardAction"
		case accessGrp = "AccessGrp"
		case vwProduct = "VwProduct"
		case vwCcardNA = "VwCcardNA"
		case organizationPersonLevel = "OrganizationPersonLevel"
		case rewardConversionPopulrty = "RewardConversionPopulrty"
		case personProperty = "PersonProperty"
		case vwRewardConversion = "VwRewardConversion"
		case role = "Role"
		case rewardType = "RewardType"
		case gallery = "Gallery"
		case productCategory = "ProductCategory"
		case file = "File"
		case vPersonLevelReward = "VPersonLevelReward"
		case lMSFunction = "LMSFunction"
		case personPropertyMapping = "PersonPropertyMapping"
		case action = "Action"
		case rewardsList = "RewardsList"
		case user = "User"
		case userRoleDataAccess = "UserRoleDataAccess"
		case vPersonPointGrade = "VPersonPointGrade"
		case systemLog = "SystemLog"
		case transactionProperty = "TransactionProperty"
		case rewardConversion = "RewardConversion"
		case userReport = "UserReport"
		case vwCcard = "VwCcard"
		case news = "News"
		case vwRewardsList = "VwRewardsList"
		case profile_Menu = "Profile_Menu"
		case transactionDetail = "TransactionDetail"
		case vwCoUser = "VwCoUser"
		case ruleManagement = "RuleManagement"
		case organizationProductCategory = "OrganizationProductCategory"
		case comment = "Comment"
		case vwRewardConversionFormula = "VwRewardConversionFormula"
		case organizationPersonGroup = "OrganizationPersonGroup"
		case ccardSegment = "CcardSegment"
		case answer = "Answer"
		case rewardConversionFormula = "RewardConversionFormula"
		case userRole = "UserRole"
		case contentCampaignPost = "ContentCampaignPost"
		case فرآيندها = "فرآيندها"
		case vPersonRewards = "VPersonRewards"
		case reward = "Reward"
		case userRewardDetail = "UserRewardDetail"
		case imageLoader = "ImageLoader"
		case userScenarioLog = "UserScenarioLog"
		case location = "Location"
	}


}
